version: "3.7"
services:
  boot_1:
    build: &node_build { 'context': '.', 'dockerfile': './apps/node/Dockerfile' }
    networks: { 'default': { 'aliases': ['boot.com'] } }

  client_1:
    build: *node_build
    environment: &client_env { 'BOOT_NODE': 'boot.com' }
  client_2:
    build: *node_build
    environment: *client_env
  client_3:
    build: *node_build
    environment: *client_env
  client_4:
    build: *node_build
    environment: *client_env
  client_5:
    build: *node_build
    environment: *client_env
  client_6:
    build: *node_build
    environment: *client_env
  client_7:
    build: *node_build
    environment: *client_env
  client_8:
    build: *node_build
    environment: *client_env
  client_9:
    build: *node_build
    environment: *client_env
  client_10:
    build: *node_build
    environment: *client_env
  client_11:
    build: *node_build
    environment: *client_env
  client_12:
    build: *node_build
    environment: *client_env
  client_13:
    build: *node_build
    environment: *client_env
  client_14:
    build: *node_build
    environment: *client_env
  client_15:
    build: *node_build
    environment: *client_env
  client_16:
    build: *node_build
    environment: *client_env
  client_17:
    build: *node_build
    environment: *client_env
  client_18:
    build: *node_build
    environment: *client_env
  client_19:
    build: *node_build
    environment: *client_env
  client_20:
    build: *node_build
    environment: *client_env


#  staker:
#    build: ./apps/staker
#
#  wallet:
#    build: ./apps/wallet
