version: "3.7"
services:
  bootstrap_node:
    build:
      context: .
      dockerfile: ./apps/node/Dockerfile
    networks:
      default:
        aliases:
          - pychain-bootstrap-node.com
    environment:
      SERVER_NAME: pychain-bootstrap-node.com
    volumes:
      - ./package:/package

  client_node:
    build:
      context: .
      dockerfile: ./apps/node/Dockerfile
    networks:
      default:
        aliases:
          - pychain-client-node.com
    environment:
      SERVER_NAME: pychain-client-node.com
    volumes:
      - ./package:/package

  staker:
    build: ./apps/staker

  wallet:
    build: ./apps/wallet
